[nmap]
name = "nmap"
cmd = "nmap -v -Pn {ip}"

  [[nmap.patterns]]
  "Discovered open port (445|139)" = [
    "SMB_SERVICE_FOUND",
    "RPC_SERVICE_FOUND"
  ]

  [[nmap.patterns]]
  "Discovered open port (389)" = [
    "LDAP_SERVICE_FOUND"
  ]

[smbclient-anonymous]
name = "smbclient-anonymous"
cmd = "smbclient -U ''%'' \\\\\\\\{ip}\\\\IPC$ -c 'AZERTY;q'"

  [[smbclient-anonymous.patterns]]
  "AZERTY: command not found" = [
    "SMB_ACCESS"
  ]

[ldap-base]
name = "ldap-base"
cmd = "ldapsearch -LLL -x -h {ip} -s base"

  [[ldap-base.store]]
  domain_name = "ldapServiceName: .*\\@(.*)$"

  [[ldap-base.store]]
  dc_dns = "dnsHostName: (.*?)$"

  [[ldap-base.store]]
  domain_dn = "rootDomainNamingContext: (.*?)$"

  [[ldap-base.patterns]]
  "rootDomainNamingContext: DC=.*$" = [
    "LDAP_DOMAIN_CONTROLLER"
  ]

[ldap-anonymous-dc]
name = "ldap-anonymous-dc"
cmd = "ldapsearch -LLL -x -h {ip} -b '{domain_dn}' > {output_dir}ldap-anonymous-dc.txt"

  [[ldap-anonymous-dc.store_static]]
  ldap_dc_output_file = "{output_dir}ldap-anonymous-dc.txt"

[rpc-anonymous]
name = "rpc-anonymous"
cmd = "rpcclient -U ''%'' {ip} -c 'AZERTY;quit' 2>/dev/null'"

  [[rpc-anonymous.patterns]]
  "command not found: AZERTY" = [
    "RPC_ACCESS"
  ]

[rpc-list-users]
name = "rpc-list-users"
cmd = """rpcclient -U ''%'' {ip} -c 'enumdomusers;quit' 2>/dev/null | cut -d[ -f2 | cut -d] -f1 > {output_dir}rpc-users.lst; 
[ -s {output_dir}rpc-users.lst ] && grep -vq 'result was' {output_dir}rpc_users.lst && echo 'USERS FOUND'"""

  [[rpc-list-users.store_static]]
  users_file = "{output_dir}rpc-users.lst"

  [[rpc-list-users.patterns]]
  "USERS FOUND" = [
    "RPC_USER_LIST"
  ]

[hydra-nsr-spraying]
name = "hydra-nsr-spraying"
cmd = "hydra -L {users_file} -e nsr smb://{ip}"

[asreproast]
name = "asreproast"
cmd = """GetNPUsers.py {domain_name}/ -usersfile {users_file} -no-pass -dc-ip {ip} -outputfile {output_dir}asreproast.hash; 
[ -s {output_dir}asreproast.hash ] && echo 'TGT FOUND'"""

  [[asreproast.store_static]]
  asreproast_hashes = "{output_dir}asreproast.hash"

  [[asreproast.patterns]]
  "TGT FOUND" = [
    "USER_TGT_FOUND"
  ]

[extract-links-html]
name = "extract-links-html"
cmd =  "Y3VybCAtcyAtTCAtayB7dXJsfSBcCnwgZ3JlcCAtRXdobyAiKHNyY3xocmVmKVsnXCJdP1xzKls9Ol1ccypbJ1wiXT9bXidcIj4gXSoiIFwKfCBhd2sgJ3t7c3BsaXQoJDAsYXJyLC8oaHJlZnxzcmMpWz06XVtcIicnXT8vKTsgcHJpbnQgYXJyWzJdfX0nIFwKfCBzb3J0IC1mdSBcCnwgZ3JlcCAtRXYgIlwuKHBuZ3xzdmd8anBnfGpwZWd8Y3NzKSIgXAp8IHNvcnQgLWZ1ID4ge291dHB1dF9kaXJ9dG1wX3VybHMubHN0OyBcCndoaWxlIHJlYWQgLXIgbGluZTsgZG8gXAppZiBbWyAhICRsaW5lID1+IGh0dHAocyk/Oi8vIF1dOyB0aGVuIFwKcHl0aG9uMyAtYyAiZnJvbSB1cmxsaWIucGFyc2UgaW1wb3J0IHVybGpvaW47IHRyeTogcHJpbnQodXJsam9pbigne3VybH0nLCAnJGxpbmUnKSk7IGV4Y2VwdDogcGFzczsiO1wKZWxzZSBcCmVjaG8gJGxpbmU7CmZpO1wKZG9uZSA8IHtvdXRwdXRfZGlyfXRtcF91cmxzLmxzdCA+PiB7b3V0cHV0X2Rpcn11cmxzLmxzdDsgXApbIC1zIHtvdXRwdXRfZGlyfXVybHMubHN0IF0gJiYgZWNobyAiVVJMUyBGT1VORCI="
base64 = true

  [[extract-links-html.store_static]]
  urls_file = "{output_dir}urls.lst"

  [[extract-links-html.patterns]]
  "URLS FOUND" = [
    "RECON_JS_FILES"
  ]

[recon-js-files]
name = "recon-js-files"
cmd = "python3 ~/programs/reconjs/reconjs.py -r -d {output_dir}reconjs -u {url}"

  [[recon-js-files.append_array]]
  "map_file_paths" = "Map file saved at (.*?)$"
  
  [[recon-js-files.patterns]]
  "Map file saved" = [
    "JS_MAP_FILE_FOUND"
  ]
  "Unminified file found !" = [
    "JS_UNMINIFIED_FILE_FOUND"
  ]

[unsourcemap]
name = "unsourcemap"
cmd = '''mkdir -p {output_dir}unsourcemap && outfile_name=`echo "{array_element}" | awk -F/ '{{ print $NF }}' | cut -d. -f1` && python3 /home/layno/programs/reconjs/unwebpack_sourcemap.py --make-directory --local {array_element} {output_dir}unsourcemap/$outfile_name/'''
iterate_over = "map_file_paths"
