[[START]]
name = "nmap"
run_once = true

[["SMB SERVICE FOUND"]]
name = "smbclient-anonymous"
run_once = true

[["LDAP SERVICE FOUND"]]
name = "ldap-base"

[["TARGET IS A DOMAIN CONTROLLER"]]
name = "ldap-anonymous-dc"
run_once = true

[["LDAP ANONYMOUS ACCESS TO DC"]]
name = "extract-ldap-users"

[["RPC SERVICE FOUND"]]
name = "rpc-anonymous"
run_once = true

[["RPC ANONYMOUS ACCESS"]]
name = "rpc-list-users"
run_once = true

